#include "surface_temperature_calculator.h"

SurfaceTemperatureCalculator::SurfaceTemperatureCalculator(double solarConstant,
                                                           const SurfaceMaterial &material,
                                                           double dayLengthDays,
                                                           RotationMode rotationMode,
                                                           const AtmosphereComposition &atmosphere,
                                                           double greenhouseOpacity,
                                                           bool manualGreenhouseOnTopOfAtmosphere,
                                                           double presetCloudAlbedo,
                                                           double atmospherePressureAtm,
                                                           double surfaceGravity,
                                                           double planetRadiusKm,
                                                           bool useAtmosphericModel,
                                                           RadiationModelType radiationModelType,
                                                           int meridionalTransportSteps,
                                                           HeightSourceType heightSourceType,
                                                           const QString &heightmapPath,
                                                           double heightmapScaleKm,
                                                           quint32 heightSeed,
                                                           bool useContinentsHeight,
                                                           bool hasSeaLevel,
                                                           bool useFlatHeight,
                                                           const SubsurfaceModelSettings &subsurfaceSettings)
    : solarConstant_(solarConstant),
      material_(material),
      dayLengthDays_(dayLengthDays),
      rotationMode_(rotationMode),
      atmosphere_(atmosphere),
      greenhouseOpacity_(qBound(0.0, greenhouseOpacity, 0.999)),
      manualGreenhouseOnTopOfAtmosphere_(manualGreenhouseOnTopOfAtmosphere),
      presetCloudAlbedo_(qBound(0.0, presetCloudAlbedo, 1.0)),
      atmospherePressureAtm_(atmospherePressureAtm),
      surfaceGravity_(surfaceGravity),
      planetRadiusKm_(planetRadiusKm),
      useAtmosphericModel_(useAtmosphericModel),
      radiationModelType_(radiationModelType),
      meridionalTransportSteps_(qMax(1, meridionalTransportSteps)),
      heightSourceType_(heightSourceType),
      heightmapPath_(heightmapPath),
      heightmapScaleKm_(heightmapScaleKm),
      heightSeed_(heightSeed),
      useContinentsHeight_(useContinentsHeight),
      hasSeaLevel_(hasSeaLevel),
      useFlatHeight_(useFlatHeight),
      subsurfaceSettings_(subsurfaceSettings) {}

void SurfaceTemperatureCalculator::setMeridionalTransportSteps(int steps) {
    meridionalTransportSteps_ = qMax(1, steps);
}
